# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"8\n\x0b\x43lientInput\x12\x14\n\x0csingle_guess\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\"6\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rgame_continue\x18\x02 \x01(\x08\x32:\n\tGameRound\x12-\n\x0cguess_letter\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTINPUT._serialized_start=14
  _CLIENTINPUT._serialized_end=70
  _SERVEROUTPUT._serialized_start=72
  _SERVEROUTPUT._serialized_end=126
  _GAMEROUND._serialized_start=128
  _GAMEROUND._serialized_end=186
# @@protoc_insertion_point(module_scope)
