# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class GameRoundStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.guess_letter = channel.unary_unary(
                '/GameRound/guess_letter',
                request_serializer=game__pb2.ClientInput.SerializeToString,
                response_deserializer=game__pb2.ServerOutput.FromString,
                )


class GameRoundServicer(object):
    """Missing associated documentation comment in .proto file."""

    def guess_letter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameRoundServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'guess_letter': grpc.unary_unary_rpc_method_handler(
                    servicer.guess_letter,
                    request_deserializer=game__pb2.ClientInput.FromString,
                    response_serializer=game__pb2.ServerOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GameRound', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameRound(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def guess_letter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GameRound/guess_letter',
            game__pb2.ClientInput.SerializeToString,
            game__pb2.ServerOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
